version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/identity
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /application_start.sh
      timeout: 300
      runas: root
